"""Materialising resolved skills into every enabled harness.

One authored skill in ``skills/`` becomes N files on disk. This module is the
only thing that writes them; nothing else should ever hand-edit the outputs.

**Ownership.** The build owns exactly the paths it emitted last time, recorded
in ``skills-lock.json``. Anything else on disk is left alone. That matters
right now: ``.agents/skills/`` still holds 76 hand-committed BMAD directories
and ``.gemini/commands/`` 77 hand-committed TOML files. Until BMAD becomes a
pack, a build must not touch them — a generator that owns a whole directory
would delete them on its first run.

**Provenance.** Each emitted file carries the pack, the pack version and a
content hash in its frontmatter, and the same triple lands in the lockfile.
Nothing changes without a visible lockfile diff, which is the mechanism that
keeps an upstream release from silently rewriting a pinned skill.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from .harnesses import load_harnesses
from .packs import SkillSource
from .resolver import Resolution

__all__ = ["BuildPlan", "BuildResult", "plan_build", "apply_build", "LOCKFILE_RELPATH"]

LOCKFILE_RELPATH = Path("skills-lock.json")
LOCK_VERSION = 1

_GENERATED_NOTE = (
    "Generated by `pnpm run skills:build` from {source}. Do not edit here — "
    "edit the source and rebuild."
)


@dataclass
class BuildPlan:
    """Every file the build wants on disk, as path -> content."""

    files: dict[Path, str] = field(default_factory=dict)
    """Text files, relative to the repo root."""
    copies: dict[Path, Path] = field(default_factory=dict)
    """Bundled resources: destination (relative) -> absolute source."""

    def all_paths(self) -> set[Path]:
        return set(self.files) | set(self.copies)


@dataclass
class BuildResult:
    written: list[Path] = field(default_factory=list)
    removed: list[Path] = field(default_factory=list)
    unchanged: list[Path] = field(default_factory=list)

    @property
    def changed(self) -> bool:
        return bool(self.written or self.removed)


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def content_hash(src: SkillSource) -> str:
    """A stable hash over everything that travels with the skill.

    Covers the SKILL.md plus every bundled file (scripts, references,
    templates), so a change to a helper script shows up as a lockfile diff the
    same way a change to the instructions does.
    """
    h = hashlib.sha256()
    if src.kind == "agent":
        h.update(src.path.read_bytes())
        return h.hexdigest()
    for f in sorted(p for p in src.dir.rglob("*") if p.is_file()):
        h.update(str(f.relative_to(src.dir)).encode("utf-8"))
        h.update(_sha256_file(f).encode("ascii"))
    return h.hexdigest()


def _render_frontmatter(meta: dict[str, Any]) -> str:
    """Emit YAML frontmatter with `name` and `description` first.

    Field order is not cosmetic: every harness reads those two, and several
    truncate long descriptions, so they must not be buried under metadata.
    """
    ordered: dict[str, Any] = {}
    for key in ("name", "description", "when_to_use", "paths"):
        if key in meta:
            ordered[key] = meta[key]
    for key, value in meta.items():
        if key not in ordered:
            ordered[key] = value
    return yaml.safe_dump(
        ordered,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=10_000,
    )


def _emit_document(
    src: SkillSource, pack_version: str, digest: str, source_rel: str
) -> str:
    """Rebuild a SKILL.md / agent file with derived provenance injected."""
    meta = dict(src.meta)
    container = (
        dict(meta.get("metadata") or {})
        if isinstance(meta.get("metadata"), dict)
        else {}
    )
    wp = (
        dict(container.get("workpilot") or {})
        if isinstance(container.get("workpilot"), dict)
        else {}
    )

    # Derived, never authored by hand — that is why they can't drift.
    wp["pack"] = src.pack
    wp["version"] = pack_version
    wp["content_sha256"] = digest
    if src.targets:
        wp["targets"] = src.targets

    container["workpilot"] = wp
    meta["metadata"] = container

    # The provenance note goes *inside* the frontmatter, as a YAML comment.
    # In the body it would be the first thing the model reads on every single
    # invocation -- pure token cost for a message aimed at humans. Here the
    # frontmatter parser strips it along with the rest of the block.
    note = _GENERATED_NOTE.format(source=source_rel)
    return f"---\n# {note}\n{_render_frontmatter(meta)}---\n\n{src.body.rstrip()}\n"


def _toml_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def _emit_gemini_command(src: SkillSource, body: str) -> str:
    description = str(src.meta.get("description", "") or "").replace("\n", " ").strip()
    return (
        f'description = "{_toml_escape(description)}"\n'
        f'prompt = """\n{body.rstrip()}\n"""\n'
    )


def _marketplace(resolution: Resolution) -> str:
    packs = sorted(resolution.packs.values(), key=lambda p: p.name)
    doc = {
        "name": "workpilot",
        "owner": {"name": "WorkPilot AI Team"},
        "plugins": [
            {
                "name": f"workpilot-{p.name}",
                "source": f"./skills/{p.name}",
                "version": p.version,
                "description": p.description,
            }
            for p in packs
        ],
    }
    return json.dumps(doc, indent="\t", ensure_ascii=False) + "\n"


def plan_build(
    source_root: Path,
    resolution: Resolution,
    harness_names: list[str] | None = None,
) -> BuildPlan:
    """Compute every output file without touching the filesystem."""
    matrix = load_harnesses(source_root)
    if harness_names:
        unknown = [h for h in harness_names if h not in matrix]
        if unknown:
            raise ValueError(f"unknown harness(es): {', '.join(unknown)}")
        enabled = [matrix[h] for h in harness_names]
    else:
        enabled = [h for h in matrix.values() if h.default]

    plan = BuildPlan()
    digests = {s.name: content_hash(s) for s in resolution.selected}

    for src in resolution.selected:
        pack_version = resolution.packs[src.pack].version
        # Relative, so the output is byte-identical on every machine --
        # otherwise `skills:check` would fail in CI on the path alone.
        source_rel = src.path.relative_to(source_root).as_posix()
        document = _emit_document(src, pack_version, digests[src.name], source_rel)

        for harness in enabled:
            if src.kind == "skill":
                if not harness.skills_path:
                    continue
                base = Path(harness.skills_path) / src.name
                plan.files[base / "SKILL.md"] = document
                # Bundled resources travel with the skill.
                for extra in sorted(p for p in src.dir.rglob("*") if p.is_file()):
                    if extra.name == "SKILL.md" and extra.parent == src.dir:
                        continue
                    plan.copies[base / extra.relative_to(src.dir)] = extra
                if harness.format == "toml-command" and harness.commands_path:
                    plan.files[Path(harness.commands_path) / f"{src.name}.toml"] = (
                        _emit_gemini_command(src, src.body)
                    )
            else:
                if not harness.agents_path:
                    continue
                plan.files[Path(harness.agents_path) / f"{src.name}.md"] = document

    plan.files[Path(".claude-plugin") / "marketplace.json"] = _marketplace(resolution)
    return plan


def _lockfile(
    source_root: Path,
    resolution: Resolution,
    plan: BuildPlan,
    harness_names: list[str],
) -> str:
    digests = {s.name: content_hash(s) for s in resolution.selected}
    doc = {
        "lockfileVersion": LOCK_VERSION,
        "note": (
            "Generated by `pnpm run skills:build`. `emitted` is what the build "
            "owns: the next build removes entries that disappear from it and "
            "touches nothing else."
        ),
        "harnesses": sorted(harness_names),
        "packs": {
            name: {
                "version": pack.version,
                "source": pack.source,
                "path": pack.path.relative_to(source_root).as_posix(),
            }
            for name, pack in sorted(resolution.packs.items())
        },
        "skills": {
            src.name: {
                "kind": src.kind,
                "pack": src.pack,
                "packVersion": resolution.packs[src.pack].version,
                "source": src.path.relative_to(source_root).as_posix(),
                "contentSha256": digests[src.name],
                "targets": src.targets or {},
            }
            for src in sorted(resolution.selected, key=lambda s: s.name)
        },
        "rejected": [
            {
                "name": r.name,
                "kind": r.kind,
                "pack": r.pack,
                "gate": r.gate,
                "reason": r.reason,
            }
            for r in sorted(resolution.rejected, key=lambda r: (r.name, r.gate))
        ],
        "emitted": sorted(p.as_posix() for p in plan.all_paths()),
    }
    return json.dumps(doc, indent="\t", ensure_ascii=False) + "\n"


def _previously_emitted(out_root: Path) -> set[Path]:
    lock = out_root / LOCKFILE_RELPATH
    if not lock.is_file():
        return set()
    try:
        data = json.loads(lock.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return set()
    return {Path(p) for p in data.get("emitted", [])}


def apply_build(
    out_root: Path,
    resolution: Resolution,
    plan: BuildPlan,
    harness_names: list[str],
    *,
    source_root: Path | None = None,
    check_only: bool = False,
) -> BuildResult:
    """Write the plan to disk, or report drift when ``check_only``.

    ``out_root`` is the *consuming project*: that is where `.agents/skills/`
    and `skills-lock.json` land. ``source_root`` is the repo the packs were
    authored in, used only to make lockfile paths relative. They are the same
    directory when building WorkPilot for itself, and different when building
    a consumer project — which is the normal case, and the reason these are
    two parameters instead of one.
    """
    source_root = source_root or out_root
    result = BuildResult()

    # The lockfile is part of the output, and its `emitted` list must describe
    # the build that produced it — so compute it before deciding what to remove.
    lock_text = _lockfile(source_root, resolution, plan, harness_names)
    wanted_files = dict(plan.files)
    wanted_files[LOCKFILE_RELPATH] = lock_text

    stale = _previously_emitted(out_root) - plan.all_paths()

    for rel, content in sorted(wanted_files.items()):
        dest = out_root / rel
        current = dest.read_text(encoding="utf-8") if dest.is_file() else None
        if current == content:
            result.unchanged.append(rel)
            continue
        result.written.append(rel)
        if not check_only:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content, encoding="utf-8")

    for rel, source in sorted(plan.copies.items()):
        dest = out_root / rel
        if dest.is_file() and _sha256_file(dest) == _sha256_file(source):
            result.unchanged.append(rel)
            continue
        result.written.append(rel)
        if not check_only:
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, dest)

    for rel in sorted(stale):
        dest = out_root / rel
        if not dest.exists():
            continue
        result.removed.append(rel)
        if not check_only:
            dest.unlink()
            # Clean up a directory the removal just emptied.
            parent = dest.parent
            while parent != out_root and parent.is_dir() and not any(parent.iterdir()):
                parent.rmdir()
                parent = parent.parent

    return result
